"""
MMM variable splitter -- hosted version.

    streamlit run app.py

Both files are uploaded in the browser and the result comes back as a
download. Nothing is written anywhere permanent: each check or run copies the
uploads into a temporary folder that is deleted when the run ends (see
splitter_service.run_isolated).

The splitting itself is unchanged -- every check and every number still comes
from mmm_splitter.cmd_split.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

import pandas as pd
import streamlit as st

import mmm_splitter as M
import splitter_service as S
from config import Campaign, Split

st.set_page_config(page_title="MMM variable splitter", layout="wide")

PASS_ICON, FAIL_ICON, WARN_ICON = "✅", "❌", "⚠️"
CURVE_LABELS = {
    "own_curve": "Own curve per campaign (built from the model)",
    "shared_shape": "Same shape, differing by cost",
    "additive": "Scaled by volume (sums to the pooled curve)",
}
_cm = S.CONFIG_DEFAULTS["CURVE_MODE"]
DEFAULT_CURVE = _cm.get("default", "shared_shape") if isinstance(_cm, dict) else _cm


# ---------------------------------------------------------------- helpers ---

def _s(v) -> str:
    """A data_editor cell as a clean string (cells can be None or NaN)."""
    if v is None or (isinstance(v, float) and v != v):
        return ""
    return str(v).strip()


def _digest(*parts) -> str:
    return hashlib.sha1(repr(parts).encode()).hexdigest()[:12]


def _file_id(f) -> str:
    return getattr(f, "file_id", None) or hashlib.sha1(f.getvalue()).hexdigest()


def ranked(cols: list[str], first: list[str]) -> list[str]:
    """Likely columns first, then the rest. Never a filtered list: the import
    file may name a channel differently from the model."""
    return first + [c for c in cols if c not in first]


def summarise(text: str) -> list[tuple[str, str]]:
    rows = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("Transform check PASSED"):
            rows.append((PASS_ICON, s))
        elif s.startswith(("Transform check FAILED", "STOPPED")):
            rows.append((FAIL_ICON, s))
        elif s.startswith(("contribution ", "spend ", "raw ")) and "->" in s:
            before, after = s.split("->", 1)
            a = re.findall(r"[\d,]+\.?\d*", before)
            b = re.findall(r"[\d,]+\.?\d*", after)
            ok = a and b and a[-1] == b[0]
            rows.append((PASS_ICON if ok else FAIL_ICON, s))
        elif s.startswith(("WARNING", "NOTE", "NO CURVE", "ACCEPTED",
                           "RESCALED", "RAW MISMATCH")):
            rows.append((WARN_ICON, s))
        elif s.startswith(("All checks passed", "Written:")):
            rows.append((PASS_ICON, s))
    return rows


def config_text(settings: dict) -> str:
    out = ["# Generated by the MMM variable splitter app. Keep this alongside",
           "# the result file as a record of exactly how it was split, or",
           "# give it to whoever maintains the tool to repeat the run exactly.",
           ""]
    for k in ("DECAY_IS_RETENTION", "CURVE_MODE", "ACCEPT_TRANSFORM_MISMATCH",
              "ACCEPT_RAW_MISMATCH", "SMOOTHING", "RESCALE_TO_POOLED"):
        out.append(f"{k} = {settings.get(k, S.CONFIG_DEFAULTS[k])!r}")
    out += ["", "SPLITS = ["]
    for sp in settings["SPLITS"]:
        out += ["    Split(", f"        pooled={sp.pooled!r},", "        campaigns=["]
        out += [f"            Campaign({c.name!r}, {c.raw!r}, {c.spend!r}),"
                for c in sp.campaigns]
        out += ["        ],", "    ),"]
    out.append("]")
    return "\n".join(out)


def show_run(r: S.RunResult, ok_text: str) -> None:
    if r.crash:
        st.error("The tool hit an unexpected error. This is a fault in the "
                 "tool, not a finding about your files. Send the message "
                 "below to whoever maintains it.")
        st.code(r.crash, language="text")
    elif r.code == 0:
        st.success(ok_text)
    else:
        st.error("Stopped. Nothing was written -- see below for what was found.")
    rows = summarise(r.output)
    if rows:
        st.subheader("What it found")
        for icon, line in rows:
            st.markdown(f"{icon} &nbsp; `{line}`", unsafe_allow_html=True)
    with st.expander("Full output", expanded=(r.code != 0 and not r.crash)):
        st.code(r.output or "(no output)", language="text")


# ------------------------------------------------------------------- page ---

st.title("MMM variable splitter")
st.caption("Replaces a combined media variable with the campaigns it was "
           "built from. Your files are held in memory for this browser "
           "session only. Each check or run copies them to a temporary folder "
           "on the server that is deleted as soon as the run ends, and the "
           "result comes back as a download. Nothing is stored.")

# --- 1. files ---------------------------------------------------------------
st.header("1 · Files")
c1, c2 = st.columns(2)
up_out = c1.file_uploader("Model output file — the one to be changed",
                          type=["xlsx", "xlsm"])
up_imp = c2.file_uploader("Import file — the one with the DATA sheet",
                          type=["xlsx", "xlsm"])
if not (up_out and up_imp):
    st.info("Upload both files to continue.")
    st.stop()

files = {"output": (up_out.name, up_out.getvalue()),
         "import": (up_imp.name, up_imp.getvalue())}
file_key = _digest(_file_id(up_out), _file_id(up_imp))

if st.session_state.get("ins_key") != file_key:
    with st.spinner("Reading both files..."):
        st.session_state.ins = S.inspect(files)
    st.session_state.ins_key = file_key
    st.session_state.prefills = {}
    for k in ("check", "result"):
        st.session_state.pop(k, None)

r_ins = st.session_state.ins
if r_ins.crash or r_ins.code:
    first = (r_ins.crash or r_ins.output or "").strip().splitlines()
    st.error("Could not read those files: " + (first[0] if first else "unknown error"))
    with st.expander("Details"):
        st.code((r_ins.output or "") + "\n" + (r_ins.crash or ""), language="text")
    st.stop()
ins: S.Inspection = r_ins.value

model_composites = [v for v in ins.variables if v in ins.composites]
st.success(f"{len(ins.variables)} variables in the model (from "
           f"'{ins.structure_sheet}'), {len(ins.data_cols)} columns on DATA, "
           f"{len(model_composites)} combined variables defined in "
           f"'{S.COMPOSITE_SHEET}'.")
for n in ins.notes:
    st.warning(n)
if not ins.has_curves:
    if ins.can_build_curves:
        st.info("This output file has no 'Response Curves' or 'T ROI curves' "
                "sheet. The app builds both from the model, with the "
                "platform's own formula, whether or not anything is split. "
                "To only add them, run the checks with no variable selected.")
    else:
        st.warning("This output file has no curve sheets, and they cannot be "
                   "built: that needs '(COSTS DEF)' and '(SPENDS DEF)' in the "
                   "output file. The split itself still works.")

ignored = [k for k in S.PER_JOB if S.CONFIG_DEFAULTS[k]]
if ignored:
    st.warning("config.py sets " + ", ".join(ignored) + ". The app ignores "
               "those and uses only what is entered below, so one job's "
               "overrides cannot carry into another's.")

# --- 2. what to split -------------------------------------------------------
st.header("2 · What to split")


def get_prefill(pooled: str) -> S.Prefill:
    cache = st.session_state.prefills
    if pooled not in cache:
        cache[pooled] = S.prefill(pooled, ins)
    return cache[pooled]


if model_composites:
    with st.expander(f"Combined variables found in '{S.COMPOSITE_SHEET}' "
                     f"({len(model_composites)})"):
        table = []
        for v in model_composites:
            pf = get_prefill(v)
            table.append({
                "Variable": v,
                "Formula": ins.composites[v]["formula"],
                "Pre-fill": {"composite": f"{len(pf.rows)} campaigns",
                             "sum-match": f"{len(pf.rows)} campaigns (by sum)",
                             "none": "fill in by hand"}[pf.source],
            })
        st.dataframe(pd.DataFrame(table), hide_index=True,
                     width="stretch")

options = model_composites + [v for v in ins.variables if v not in ins.composites]
selected = st.multiselect(
    "Combined variables to split", options, key=f"sel::{file_key}",
    format_func=lambda v: f"{v}  (composite)" if v in ins.composites else v,
    help="Composites from the model file are listed first and pre-filled. "
         "A variable combined outside the platform is pre-filled when a set "
         "of its channel's DATA columns sums exactly to it.")

splits: list[Split] = []
curve_modes, smoothing, acc_transform, acc_raw, rescale = {}, {}, {}, {}, {}
problems: list[str] = []

for pooled in selected:
    pf = get_prefill(pooled)
    ek = f"{file_key}::{pooled}"
    with st.container(border=True):
        st.subheader(pooled)
        st.caption({
            "composite": f"Pre-filled from the formula `{pf.formula}`.",
            "sum-match": "Pre-filled: these DATA columns sum exactly to the "
                         "pooled variable's Raw series.",
            "none": "Nothing to pre-fill from. Add one row per campaign.",
        }[pf.source])
        for n in pf.notes:
            st.info(n)

        rows = [{k: (v or None) for k, v in r.items()} for r in pf.rows] \
            or [{"name": None, "raw": None, "spend": None}] * 2
        channel = S.split_name(pooled)[0]
        likely_raw = S.likely_columns(ins.data_cols, pooled)
        likely_spend = [c for c in ins.data_cols if S.split_name(c)[0] == channel
                        and S.split_name(c)[1] in S.SPEND_TOKENS]
        edited = st.data_editor(
            pd.DataFrame(rows, columns=["name", "raw", "spend"]),
            key=f"ed::{ek}", num_rows="dynamic", hide_index=True,
            width="stretch",
            column_config={
                "name": st.column_config.TextColumn(
                    "New variable name",
                    help="Leave blank to use the metric column's name."),
                "raw": st.column_config.SelectboxColumn(
                    "Column with the modelled metric",
                    options=ranked(ins.data_cols, likely_raw),
                    help="The impressions, clicks or GRPs the model was built on."),
                "spend": st.column_config.SelectboxColumn(
                    "Column with spend",
                    options=ranked(ins.data_cols, likely_spend)),
            })

        camps, bad = [], []
        for i, row in edited.reset_index(drop=True).iterrows():
            nm, raw, sp = _s(row["name"]), _s(row["raw"]), _s(row["spend"])
            if not (nm or raw or sp):
                continue                                   # empty row
            if not raw or not sp:
                bad.append(f"row {i + 1} needs both a metric and a spend column")
                continue
            camps.append(Campaign(nm or raw, raw, sp))
        names = [c.name for c in camps]
        if len(camps) < 2:
            bad.append("at least two campaigns are needed")
        if len(set(names)) != len(names):
            bad.append("two campaigns have the same name")
        if pooled in names:
            bad.append("a campaign has the pooled variable's own name")
        raws = [c.raw for c in camps]
        if len(set(raws)) != len(raws):
            bad.append("the same metric column is used twice")
        problems += [f"**{pooled}**: {b}" for b in bad]

        on_spend = [c.raw == c.spend for c in camps]
        a, b = st.columns([3, 2])
        mode_opts = list(CURVE_LABELS)
        default_mode = ("additive" if (camps and all(on_spend)
                                       and DEFAULT_CURVE == "shared_shape")
                        else DEFAULT_CURVE)
        mode = a.radio("Response curves", mode_opts, horizontal=True,
                       index=mode_opts.index(default_mode), key=f"cm::{ek}",
                       format_func=CURVE_LABELS.get)
        if camps and all(on_spend) and mode == "shared_shape":
            a.warning("Metric and spend are the same columns, so this variable "
                      "was modelled on spend. Same-shape curves would come out "
                      "identical -- use 'Scaled by volume'.")
        elif any(on_spend) and not all(on_spend):
            a.warning("Some rows use the spend column as the metric and some "
                      "do not. The pooled variable has one unit, so one of "
                      "these is probably the wrong column.")
        curve_modes[pooled] = mode

        sm0 = pf.smoothing or {}
        win = b.number_input("Smoothing before modelling (days, 1 = none)",
                             1, 90, int(sm0.get("window", 1)), key=f"sw::{ek}",
                             help="Pre-filled when the composite formula is "
                                  "a bma/cma average.")
        cen = b.checkbox("Centred", value=bool(sm0.get("centred", False)),
                         key=f"sc::{ek}")
        if win > 1:
            smoothing[pooled] = {"window": int(win), "centred": bool(cen)}

        with st.expander("Diagnose this variable"):
            st.caption("For when the checks stop on this variable. Each one "
                       "reads both files and writes nothing.")
            d1, d2 = st.columns(2)
            which = None
            if d1.button("Which columns are missing?", key=f"dsum::{ek}",
                         disabled=len(camps) < 1,
                         help="When the campaigns do not add up to the "
                              "combined variable: finds DATA columns that "
                              "would account for the gap."):
                which = "sum"
            if d2.button("Was it smoothed before modelling?", key=f"dsm::{ek}",
                         disabled=len(camps) < 1,
                         help="When the totals match but individual days do "
                              "not: tests rolling averages of the campaigns."):
                which = "smoothing"
            if which:
                with st.spinner("Diagnosing..."):
                    st.session_state[f"diag::{ek}"] = S.diagnose(
                        files, {"SPLITS": [Split(pooled=pooled, campaigns=camps)]},
                        which, pooled)
            dres = st.session_state.get(f"diag::{ek}")
            if dres is not None:
                st.code((dres.output or "") + (dres.crash or ""), language="text")

        with st.expander("Overrides -- only once a diagnosis shows it is safe"):
            st.caption("Each one is a recorded decision, not a switch: the "
                       "reason is printed in the run output, and the tool "
                       "still measures whether it holds and refuses if not.")
            for store, label, hint in (
                (acc_transform, "Accept a failed transform check",
                 "e.g. scores 0.98 for reasons unrelated to decay; campaign "
                 "shares move 0.003pp"),
                (rescale, "Treat the pooled figure as authoritative on "
                          "hand-adjusted days",
                 "e.g. 5 days in June replaced with a typed average"),
                (acc_raw, "Accept that the pooled Raw is wrong and the "
                          "campaign columns are right",
                 "e.g. Raw wrongly includes one component (0.38%), confirmed "
                 "with the modeller"),
            ):
                reason = st.text_input(f"{label} — reason", key=f"{label}::{ek}",
                                       placeholder=hint).strip()
                if reason:
                    store[pooled] = reason

    if camps:
        splits.append(Split(pooled=pooled, campaigns=camps))

build_only = not selected and not ins.has_curves and ins.can_build_curves
if not selected and not build_only:
    st.info("Pick at least one combined variable.")
    st.stop()
if build_only:
    st.caption("Nothing selected to split: the run will only add the two "
               "curve sheets. Every other sheet stays exactly as it is.")

# --- 3. settings ------------------------------------------------------------
st.header("3 · Settings")
st.caption("Decay is read as **the share that decays away** each period"
           if not S.CONFIG_DEFAULTS["DECAY_IS_RETENTION"] else
           "Decay is read as **the share that carries over** each period")
with st.expander("Sheet names and other settings, read from config.py"):
    st.table(pd.DataFrame({
        "setting": ["Model structure sheet", "Alternatives tried",
                    "Daily variables sheet", "Spends sheet",
                    "Contributions sheet", "Response curves sheet",
                    "Import data sheet", "Date column", "Sheets left untouched"],
        "value": [S.CONFIG_DEFAULTS["STRUCTURE_SHEET"],
                  ", ".join(M.STRUCTURE_SHEET_ALTERNATIVES), M.DATASHEET,
                  M.SPENDS_SHEET, M.CONTRIB_SHEET, M.CURVES_SHEET, M.DATA_SHEET,
                  str(M.DATA_DATE_COL or f"found automatically ({ins.date_col})"),
                  ", ".join(sorted(M.UNTOUCHED)) or "none"],
    }))

settings = {
    "SPLITS": splits,
    "CURVE_MODE": {"default": DEFAULT_CURVE, **curve_modes},
    "ACCEPT_TRANSFORM_MISMATCH": acc_transform,
    "ACCEPT_RAW_MISMATCH": acc_raw,
    "SMOOTHING": smoothing,
    "RESCALE_TO_POOLED": rescale,
}
fingerprint = _digest(file_key, repr(settings))

# --- 4. check ---------------------------------------------------------------
st.header("4 · Check")
st.caption("Reads both files and verifies everything. Writes nothing.")

if problems:
    for p in problems:
        st.warning(p)
if st.button("Run checks", type="primary", disabled=bool(problems)):
    with st.spinner("Checking... (runs wait their turn if someone else is "
                    "checking at the same moment)"):
        st.session_state.check = {"fp": fingerprint,
                                  "r": S.split(files, settings, apply=False)}
    st.session_state.pop("result", None)

check = st.session_state.get("check")
check_ok = False
if check:
    if check["fp"] != fingerprint:
        st.warning("Something above has changed since these checks ran. Run "
                   "them again before generating the file.")
    else:
        r = check["r"]
        check_ok = r.code == 0 and not r.crash
        show_run(r, "All checks passed. Nothing has been written yet.")
        if not check_ok and not r.crash:
            st.info("**Do not work around this.** The message names what it "
                    "found. If the campaigns do not add up, open **Diagnose "
                    "this variable** in step 2. If a transform check failed, "
                    "the output above already shows how far the split would "
                    "move. If the cause is not clear, send the full output to "
                    "whoever maintains the tool.")

# --- 5. generate ------------------------------------------------------------
st.header("5 · Generate the file")
if not check_ok:
    st.button("Generate the file", disabled=True)
    st.caption("Available once the checks have run and passed on exactly "
               "these settings.")
else:
    dest = st.text_input("Name for the new file",
                         value=f"{Path(up_out.name).stem}_split.xlsx").strip()
    if not dest.lower().endswith((".xlsx", ".xlsm")):
        dest += ".xlsx"
    if st.button("Generate the file", type="primary"):
        with st.spinner("Writing..."):
            st.session_state.result = {
                "fp": fingerprint, "name": dest,
                "r": S.split(files, settings, apply=True, dest_name=dest)}

    res = st.session_state.get("result")
    if res and res["fp"] == fingerprint:
        r = res["r"]
        if r.code == 0 and not r.crash and r.written:
            st.download_button(f"Download {res['name']}", data=r.written,
                               file_name=res["name"], type="primary",
                               mime="application/vnd.openxmlformats-"
                                    "officedocument.spreadsheetml.sheet")
            st.caption("The file is client data like any model output. Save "
                       "it where you keep those, not in a shared folder.")
        elif r.code == 0 and not r.crash:
            st.error("The run reported success but produced no file. Send "
                     "the full output to whoever maintains the tool.")
        show_run(r, "Generated.")

# --- record -----------------------------------------------------------------
if (splits or build_only) and not problems:
    with st.expander("Settings as a config file"):
        text = config_text({**settings, "DECAY_IS_RETENTION":
                            S.CONFIG_DEFAULTS["DECAY_IS_RETENTION"]})
        st.code(text, language="python")
        st.download_button("Download as split_settings.py", text,
                           file_name="split_settings.py")
